# Generated by Django 4.2.7 on 2025-07-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(verbose_name='Contenu détaillé')),
                ('news_type', models.CharField(choices=[('conference', 'Conférence'), ('lancement', 'Lancement'), ('symposium', 'Symposium'), ('table_ronde', 'Table ronde'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type d'actualité")),
                ('event_date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('organizers', models.JSONField(default=list, verbose_name='Organisateurs')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Abonnement newsletter',
                'verbose_name_plural': 'Abonnements newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('partner_type', models.CharField(blank=True, max_length=100, verbose_name='Type de partenaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('partnership_type', models.CharField(blank=True, max_length=100, verbose_name='Type de partenariat souhaité')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('theme', models.CharField(max_length=300, verbose_name='Thème')),
                ('objectives', models.JSONField(default=list, verbose_name='Objectifs')),
                ('partners', models.JSONField(default=list, verbose_name='Partenaires')),
                ('results', models.JSONField(default=list, verbose_name='Résultats')),
                ('sdgs', models.JSONField(default=list, verbose_name='Objectifs de développement durable')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('planifie', 'Planifié'), ('suspendu', 'Suspendu')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet en vedette')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('authors', models.JSONField(default=list, verbose_name='Auteurs')),
                ('abstract', models.TextField(verbose_name='Résumé')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('publication_type', models.CharField(choices=[('article', 'Article scientifique'), ('rapport', 'Rapport'), ('livre', 'Livre'), ('these', 'Thèse'), ('autre', 'Autre')], default='article', max_length=20, verbose_name='Type de publication')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='Journal/Éditeur')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('publication_date', models.DateField(verbose_name='Date de publication')),
                ('keywords', models.JSONField(default=list, verbose_name='Mots-clés')),
                ('file', models.FileField(blank=True, upload_to='publications/', verbose_name='Fichier PDF')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('position', models.CharField(max_length=100, verbose_name='Poste')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Photo')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('resource_type', models.CharField(choices=[('document', 'Document'), ('video', 'Vidéo'), ('audio', 'Audio'), ('lien', 'Lien externe'), ('autre', 'Autre')], default='document', max_length=20, verbose_name='Type de ressource')),
                ('file', models.FileField(blank=True, upload_to='resources/', verbose_name='Fichier')),
                ('external_url', models.URLField(blank=True, verbose_name='URL externe')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projets',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.news', verbose_name='Actualité')),
            ],
            options={
                'verbose_name': "Image d'actualité",
                'verbose_name_plural': "Images d'actualités",
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
