# Generated by Django 4.2.7 on 2025-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
    ]
