# Generated by Django 5.2.4 on 2025-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teammember_facebook_teammember_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='interest_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domaine d’intérêt'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='participation_mode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mode de participation'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste ou fonction'),
        ),
    ]
