# Generated by Django 5.2.4 on 2025-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eventregistration_interest_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('value', models.CharField(max_length=50, verbose_name='Valeur')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[('award', 'Award'), ('users', 'Users'), ('building', 'Building'), ('book', 'Book'), ('globe', 'Globe'), ('target', 'Target')], default='award', max_length=20, verbose_name='Icône')),
                ('color', models.CharField(choices=[('blue', 'Bleu'), ('purple', 'Violet'), ('orange', 'Orange'), ('green', 'Vert'), ('red', 'Rouge'), ('pink', 'Rose')], default='blue', max_length=20, verbose_name='Couleur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['order', 'title'],
            },
        ),
    ]
