# Generated by Django 5.2.4 on 2025-08-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('recherche', 'Recherche'), ('institutionnel', 'Institutionnel'), ('partenaire', 'Partenaire'), ('ressource', 'Ressource'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (nom de classe)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lien externe',
                'verbose_name_plural': 'Liens externes',
                'ordering': ['order', 'title'],
            },
        ),
    ]
