# Generated by Django 5.2.4 on 2025-08-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_externallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
